CREATE TABLE IF NOT EXISTS RULE_TYPES
(
    ID           BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    NAME         VARCHAR(255)          NOT NULL UNIQUE,
    PARAMS_COUNT INT                   NOT NULL,
    CREATED_AT   DATETIME              NOT NULL,
    UPDATED_AT   DATETIME              NULL
);

CREATE TABLE IF NOT EXISTS RULES
(
    ID           BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    RULE_TYPE_ID BIGINT                NOT NULL,
    PARAMETERS   VARCHAR(1000)         NOT NULL,
    CREATED_AT   DATETIME              NOT NULL,
    UPDATED_AT   DATETIME              NULL,

    FOREIGN KEY (RULE_TYPE_ID)
        REFERENCES RULE_TYPES (ID)
);
